CREATE DATABASE IF NOT EXISTS anonyme_tchat CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE anonyme_tchat;

CREATE TABLE IF NOT EXISTS salons (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    salon_id INT NOT NULL,
    content TEXT NOT NULL,
    is_pinned TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_messages_salon FOREIGN KEY (salon_id) REFERENCES salons(id) ON DELETE CASCADE
);
